### ISSUE TITLE
Problem Tracker

### ISSUE THREAD

**Issue by MrTarantula** [MrTarantula/WIPrint#6]
I will track the progress of all of the major problems/suggestions here.

- [ ] **BUG** Cannot print from IE11 #5 `In progress`
- [ ] **BUG** Sort field names in TFS 2015 #3 `In progress`
- [ ] **BUG** Printing blocks everything #4 
- [ ] **FEATURE** Configurable fields per work item type #4 
- [ ] **FEATURE** Complete discussion history #2
- [ ] **FEATURE** Hide undefined fields #3 
- [ ] **FEATURE** Better fieldpicker controls/behavior #4 `In progress`
